name: flutter_resource_generator
email: bencze.balazs@yahooc.om
homepage: https://github.com/himamis/flutter_resource_generator
version: 1.0.3
description: Automatically generate a resource file by scanning pubspec.yaml to correspond to the flutter's asset.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.1
  dart_style: ^2.0.2
  glob: ^2.0.1
  io: ^1.0.3
  path: ^1.8.0
  yaml: ^3.1.0
  recase: ^4.0.0

executables:
  generate: resource_generator
